language: objective-c
osx_image: xcode10
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=Example.xcodeproj
  - IOS_FRAMEWORK_SCHEME="StatefulViewController-iOS"
  - TVOS_FRAMEWORK_SCHEME="StatefulViewController-tvOS"
  matrix:
    - DESTINATION="OS=12.0,name=iPhone 8"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="iphonesimulator12.0"
    #- DESTINATION="OS=10.0,name=Apple TV 1080p"    SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="appletvsimulator10.0"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
